// src/app/sitemap/layout.tsx
import { Metadata } from "next";
import { Suspense, ReactNode } from "react";

export const metadata: Metadata = {
  title: "Sitemap",
  description: "Generated by create next app",
};

// ✅ Define the Props type with children
type Props = {
  children: ReactNode;
};

export default function SitemapLayout({ children }: Props) {
  return <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>;
}
