// sitemap layout
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Sitemap',
    description: 'Generated by create next app',
};

export default function SitemapLayout({ children }: Props) {
    return (
        <Suspense fallback={<div>Loading...</div>}>
            {children}
        </Suspense>
    );
}