// sitemap page
import Sitemap from '@/components/SiteMap';
import { Suspense } from 'react';

export const metadata = {
    title: 'Sitemap',
    description: 'Generated by create next app',
};

export default function SitemapPage() {
    return (
        <Suspense fallback={<div>Loading...</div>}>
            <Sitemap/>
        </Suspense>
    );
}