import { Suspense } from 'react';
import { ReactNode } from 'react';

type Props = {
  children: ReactNode;
};

export const metadata = {
    title: 'ReportForm',
    description: 'Generated by create next app',
};

export default function ReportFormLayout({ children }: Props) {
    return (
        <Suspense fallback={<div>Loading...</div>}>
            {children}
        </Suspense>
    );
}
