// app/reportform/page.tsx
import { Suspense } from 'react';
import ReportForm from '@/components/ReportForm';

export const metadata = {
  title: 'ReportForm',
  description: 'Generated by create next app',
};

export default function ReportFormPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <ReportForm />
    </Suspense>
  );
}
